### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by InToSSH** [mikey0000/HA-Luba#9]
Hello,
so after setting up ESP32 proxy, the integration found the Luba successfuly, however upon adding it to HA, it says "Failed setup, will retry", it retries, but never succeeds. I tried removing and readding the Luba, that did not help.
This is what I found in the log

```
This error originated from a custom integration.

Logger: custom_components.mammotion
Source: helpers/update_coordinator.py:315
integration: Mammotion
First occurred: 2:27:53 AM (14 occurrences)
Last logged: 2:41:56 AM

Unexpected error fetching Mammotion Lawn Mower data data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 57, in _async_update_data
    return await self.device.start_sync(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyluba/mammotion/devices/luba.py", line 189, in start_sync
    plan = await self._send_command_with_args("read_plan", **{'id': 2})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyluba/mammotion/devices/luba.py", line 254, in _send_command_with_args
    raise RuntimeError("Unreachable")
RuntimeError: Unreachable
```
The ESP32 is about 3m away with line of sight to Luba.

**Comment by mikey0000** [comment]
Give it some time, the requests sometimes fail at random, working on this problem.

4/06/2024 12:45:46 pm Jarda T. ***@***.***>:

**Comment by InToSSH** [comment]
Thanks, what actually helped was to start a task on the mower and it immediatelly synced.
